---
- name: A playbook to demonstrate set_stats in a workflow
  hosts: xerxes.thenorvilles.com

  tasks:

    - name: Display a message
      ansible.builtin.debug:
        msg: "Welcome my son to the Machine...."

    - name: Fact Dump
      ansible.builtin.debug:
        var: ansible_facts

    - name: Set set_stats per_host true and aggregate true
      ansible.builtin.set_stats:
        data:
          dist_version_per_host_true_agg_true: "{{ ansible_facts.distribution_version }}"
        per_host: true
        aggregate: true

    - name: Set set_stats per_host true and aggregate false
      ansible.builtin.set_stats:
        data:
          dist_versionper_host_true_agg_false: "{{ ansible_facts.distribution_version }}"
        per_host: true
        aggregate: false

    - name: Set set_stats per_host false and aggregate true
      ansible.builtin.set_stats:
        data:
          dist_versionper_host_false_agg_true: "{{ ansible_facts.distribution_version }}"
        per_host: false
        aggregate: true

    - name: Set set_stats per_host false and aggregate false
      ansible.builtin.set_stats:
        data:
          dist_versionper_host_false_agg_false: "{{ ansible_facts.distribution_version }}"
        per_host: false
        aggregate: false
